# MoneyPrinterTurbo configuration example

log_level = "DEBUG"
listen_host = "0.0.0.0"
listen_port = 8080

[app]
llm_provider = "deepseek"
deepseek_api_key = ""
deepseek_base_url = ""
deepseek_model_name = ""
volcengine_api_key = ""
volcengine_model_name = "doubao-seedance-1-0-pro-fast-251015"
openai_api_key = ""
moonshot_api_key = ""
qwen_api_key = ""
gemini_api_key = ""
video_source = "local"
ffmpeg_path = "ffmpeg"

[whisper]
model_size = "large-v3"
device = "cpu"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[ui]
hide_log = false
